<!-- spinning icon -->
<script>
  export let className;
</script>

<!-- <?xml version="1.0" encoding="utf-8"?> -->
<svg
  class={className}
  xmlns="http://www.w3.org/2000/svg"
  xmlns:xlink="http://www.w3.org/1999/xlink"
  style="margin: auto; display: block; shape-rendering: auto;"
  width="36"
  height="36"
  viewBox="0 0 100 100"
  preserveAspectRatio="xMidYMid"
>
  <g>
    <path
      d="M50 16A34 34 0 1 0 67.76495120034228 21.010234411960877"
      fill="none"
      stroke="#708090"
      stroke-width="20"
    />
    <path d="M49 3L49 29L62 16L49 3" fill="#708090" />
    <animateTransform
      attributeName="transform"
      type="rotate"
      repeatCount="indefinite"
      dur="1s"
      values="0 50 50;360 50 50"
      keyTimes="0;1"
    />
  </g>
  <!-- [ldio] generated by https://loading.io/ --></svg
>
